name = "ooki-game"
main = "worker/src/index.ts"
compatibility_date = "2024-04-01"
workers_dev = true

routes = [
  { pattern = "al-mahalla.ahmed1986y.com/*", zone_name = "ahmed1986y.com" }
]

[vars]
ZEGO_APP_ID = "1477087305"
DOMAIN = "ahmed1986y.com"
API_DOMAIN = "al-mahalla.ahmed1986y.com"

[[d1_databases]]
binding = "DB"
database_name = "al_mahalla_db"
database_id = "d46ccf78-6560-4ab9-9680-2dd54b2e088f"

[[kv_namespaces]]
binding = "SESSIONS"
id = "4980f3da6e8e4d63b498a792aa259111"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "al-mahalla-media"

[durable_objects]
bindings = [
  { name = "CHAT_ROOM", class_name = "ChatRoomDO" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoomDO"]
