import { QuranJuz } from './types';

export const QURAN_AJZA: QuranJuz[] = [
  { number: 1, name: 'الجزء الأول', startSurahName: 'الفاتحة', startAyah: 1, endSurahName: 'البقرة', endAyah: 141, surahsIncluded: ['الفاتحة', 'البقرة'] },
  { number: 2, name: 'الجزء الثاني', startSurahName: 'البقرة', startAyah: 142, endSurahName: 'البقرة', endAyah: 252, surahsIncluded: ['البقرة'] },
  { number: 3, name: 'الجزء الثالث', startSurahName: 'البقرة', startAyah: 253, endSurahName: 'آل عمران', endAyah: 92, surahsIncluded: ['البقرة', 'آل عمران'] },
  { number: 4, name: 'الجزء الرابع', startSurahName: 'آل عمران', startAyah: 93, endSurahName: 'النساء', endAyah: 23, surahsIncluded: ['آل عمران', 'النساء'] },
  { number: 5, name: 'الجزء الخامس', startSurahName: 'النساء', startAyah: 24, endSurahName: 'النساء', endAyah: 147, surahsIncluded: ['النساء'] },
  { number: 6, name: 'الجزء السادس', startSurahName: 'النساء', startAyah: 148, endSurahName: 'المائدة', endAyah: 81, surahsIncluded: ['النساء', 'المائدة'] },
  { number: 7, name: 'الجزء السابع', startSurahName: 'المائدة', startAyah: 82, endSurahName: 'الأنعام', endAyah: 110, surahsIncluded: ['المائدة', 'الأنعام'] },
  { number: 8, name: 'الجزء الثامن', startSurahName: 'الأنعام', startAyah: 111, endSurahName: 'الأعراف', endAyah: 87, surahsIncluded: ['الأنعام', 'الأعراف'] },
  { number: 9, name: 'الجزء التاسع', startSurahName: 'الأعراف', startAyah: 88, endSurahName: 'الأنفال', endAyah: 40, surahsIncluded: ['الأعراف', 'الأنفال'] },
  { number: 10, name: 'الجزء العاشر', startSurahName: 'الأنفال', startAyah: 41, endSurahName: 'التوبة', endAyah: 92, surahsIncluded: ['الأنفال', 'التوبة'] },
  { number: 11, name: 'الجزء الحادي عشر', startSurahName: 'التوبة', startAyah: 93, endSurahName: 'هود', endAyah: 5, surahsIncluded: ['التوبة', 'يونس', 'هود'] },
  { number: 12, name: 'الجزء الثاني عشر', startSurahName: 'هود', startAyah: 6, endSurahName: 'يوسف', endAyah: 52, surahsIncluded: ['هود', 'يوسف'] },
  { number: 13, name: 'الجزء الثالث عشر', startSurahName: 'يوسف', startAyah: 53, endSurahName: 'إبراهيم', endAyah: 52, surahsIncluded: ['يوسف', 'الرعد', 'إبراهيم'] },
  { number: 14, name: 'الجزء الرابع عشر', startSurahName: 'الحجر', startAyah: 1, endSurahName: 'النحل', endAyah: 128, surahsIncluded: ['الحجر', 'النحل'] },
  { number: 15, name: 'الجزء الخامس عشر', startSurahName: 'الإسراء', startAyah: 1, endSurahName: 'الكهف', endAyah: 74, surahsIncluded: ['الإسراء', 'الكهف'] },
  { number: 16, name: 'الجزء السادس عشر', startSurahName: 'الكهف', startAyah: 75, endSurahName: 'طه', endAyah: 135, surahsIncluded: ['الكهف', 'مريم', 'طه'] },
  { number: 17, name: 'الجزء السابع عشر', startSurahName: 'الأنبياء', startAyah: 1, endSurahName: 'الحج', endAyah: 78, surahsIncluded: ['الأنبياء', 'الحج'] },
  { number: 18, name: 'الجزء الثامن عشر', startSurahName: 'المؤمنون', startAyah: 1, endSurahName: 'الفرقان', endAyah: 20, surahsIncluded: ['المؤمنون', 'النور', 'الفرقان'] },
  { number: 19, name: 'الجزء التاسع عشر', startSurahName: 'الفرقان', startAyah: 21, endSurahName: 'النمل', endAyah: 55, surahsIncluded: ['الفرقان', 'الشعراء', 'النمل'] },
  { number: 20, name: 'الجزء العشرون', startSurahName: 'النمل', startAyah: 56, endSurahName: 'العنكبوت', endAyah: 45, surahsIncluded: ['النمل', 'القصص', 'العنكبوت'] },
  { number: 21, name: 'الجزء الحادي والعشرون', startSurahName: 'العنكبوت', startAyah: 46, endSurahName: 'الأحزاب', endAyah: 30, surahsIncluded: ['العنكبوت', 'الروم', 'لقمان', 'السجدة', 'الأحزاب'] },
  { number: 22, name: 'الجزء الثاني والعشرون', startSurahName: 'الأحزاب', startAyah: 31, endSurahName: 'يس', endAyah: 27, surahsIncluded: ['الأحزاب', 'سبأ', 'فاطر', 'يس'] },
  { number: 23, name: 'الجزء الثالث والعشرون', startSurahName: 'يس', startAyah: 28, endSurahName: 'الزمر', endAyah: 31, surahsIncluded: ['يس', 'الصافات', 'ص', 'الزمر'] },
  { number: 24, name: 'الجزء الرابع والعشرون', startSurahName: 'الزمر', startAyah: 32, endSurahName: 'فصلت', endAyah: 46, surahsIncluded: ['الزمر', 'غافر', 'فصلت'] },
  { number: 25, name: 'الجزء الخامس والعشرون', startSurahName: 'فصلت', startAyah: 47, endSurahName: 'الجاثية', endAyah: 37, surahsIncluded: ['فصلت', 'الشورى', 'الزخرف', 'الدخان', 'الجاثية'] },
  { number: 26, name: 'الجزء السادس والعشرون', startSurahName: 'الأحقاف', startAyah: 1, endSurahName: 'الذاريات', endAyah: 30, surahsIncluded: ['الأحقاف', 'محمد', 'الفتح', 'الحجرات', 'ق', 'الذاريات'] },
  { number: 27, name: 'الجزء السابع والعشرون', startSurahName: 'الذاريات', startAyah: 31, endSurahName: 'الحديد', endAyah: 29, surahsIncluded: ['الذاريات', 'الطور', 'النجم', 'القمر', 'الرحمن', 'الواقعة', 'الحديد'] },
  { number: 28, name: 'الجزء الثامن والعشرون (قد سمع)', startSurahName: 'المجادلة', startAyah: 1, endSurahName: 'التحريم', endAyah: 12, surahsIncluded: ['المجادلة', 'الحشر', 'الممتحنة', 'الصف', 'الجمعة', 'المنافقون', 'التغابن', 'الطلاق', 'التحريم'] },
  { number: 29, name: 'الجزء التاسع والعشرون (تبارك)', startSurahName: 'الملك', startAyah: 1, endSurahName: 'المرسلات', endAyah: 50, surahsIncluded: ['الملك', 'القلم', 'الحاقة', 'المعارج', 'نوح', 'الجن', 'المزمل', 'المدثر', 'القيامة', 'الإنسان', 'المرسلات'] },
  { number: 30, name: 'الجزء الثلاثون (عمّ)', startSurahName: 'النبأ', startAyah: 1, endSurahName: 'الناس', endAyah: 6, surahsIncluded: ['النبأ', 'النازعات', 'عبس', 'التكوير', 'الانفطار', 'المطففين', 'الانشقاق', 'البروج', 'الطارق', 'الأعلى', 'الغاشية', 'الفجر', 'البلد', 'الشمس', 'الليل', 'الضحى', 'الشرح', 'التين', 'العلق', 'القدر', 'البينة', 'الزلزلة', 'العاديات', 'القارعة', 'التكاثر', 'العصر', 'الهمزة', 'الفيل', 'قريش', 'الماعون', 'الكوثر', 'الكافرون', 'النصر', 'المسد', 'الإخلاص', 'الفلق', 'الناس'] }
];
